<?php 
$area = array(
    array('label'=>"Select", 'id'=>"undefined",'data'=>"0",'parentid'=>"undefined"),
    array('label'=>"Auckland Central", 'id'=>"10118",'data'=>"AucklandCentral",'parentid'=>"1018"),
    array('label'=>"Bayside & Eastern Suburbs", 'id'=>"10011",'data'=>"BaysideEasternSuburbs",'parentid'=>"1004"),
    array('label'=>"Bayside & South Eastern Suburbs", 'id'=>"10070",'data'=>"BaysideSouthEasternSuburbs",'parentid'=>"1002"),
    array('label'=>"Blenheim", 'id'=>"10080",'data'=>"Blenheim",'parentid'=>"10079"),
    array('label'=>"Caribbean, Central & South America", 'id'=>"10138",'data'=>"CaribbeanCentralSouthAmerica",'parentid'=>"10137"),
    array('label'=>"CBD & Inner Suburbs", 'id'=>"10069",'data'=>"MelbourneCBDInnerSuburbs",'parentid'=>"1002"),
    array('label'=>"CBD & Inner Suburbs", 'id'=>"10010",'data'=>"BrisbaneCBDInnerSuburbs",'parentid'=>"1004"),
    array('label'=>"CBD, Inner & Western Suburbs", 'id'=>"10048",'data'=>"CBDInnerWesternSuburbs",'parentid'=>"1009"),
    array('label'=>"CBD, Inner West & Eastern Suburbs", 'id'=>"10027",'data'=>"CBDInnerWestEasternSuburbs",'parentid'=>"1000"),
    array('label'=>"Central Asia", 'id'=>"10141",'data'=>"CentralAsia",'parentid'=>"10140"),
    array('label'=>"Channel Islands", 'id'=>"10151",'data'=>"ChannelIslands",'parentid'=>"10150"),
    array('label'=>"China, Hong Kong & Taiwan", 'id'=>"10142",'data'=>"ChinaHongKongTaiwan",'parentid'=>"10140"),
    array('label'=>"Christchurch", 'id'=>"10114",'data'=>"Christchurch",'parentid'=>"10113"),
    array('label'=>"Dunedin", 'id'=>"10094",'data'=>"Dunedin",'parentid'=>"10093"),
    array('label'=>"Eastern Suburbs", 'id'=>"10049",'data'=>"PerthEasternSuburbs",'parentid'=>"1009"),
    array('label'=>"Eastern Suburbs", 'id'=>"10071",'data'=>"MelbourneEasternSuburbs",'parentid'=>"1002"),
    array('label'=>"Fremantle & Southern Suburbs", 'id'=>"10050",'data'=>"FremantleSouthernSuburbs",'parentid'=>"1009"),
    array('label'=>"Gisborne", 'id'=>"10105",'data'=>"Gisborne",'parentid'=>"10104"),
    array('label'=>"Greymouth", 'id'=>"10124",'data'=>"Greymouth",'parentid'=>"10123"),
    array('label'=>"Hamilton", 'id'=>"10127",'data'=>"Hamilton",'parentid'=>"10126"),
    array('label'=>"Hastings", 'id'=>"10086",'data'=>"Hastings",'parentid'=>"10085"),
    array('label'=>"Hutt Valley", 'id'=>"10107",'data'=>"HuttValley",'parentid'=>"1019"),
    array('label'=>"India & South Asia", 'id'=>"10143",'data'=>"IndiaSouthAsia",'parentid'=>"10140"),
    array('label'=>"Invercargill", 'id'=>"10111",'data'=>"Invercargill",'parentid'=>"10110"),
    array('label'=>"Japan & Korea", 'id'=>"10144",'data'=>"JapanKorea",'parentid'=>"10140"),
    array('label'=>"Manukau & East Auckland", 'id'=>"10119",'data'=>"ManukauEastAuckland",'parentid'=>"1018"),
    array('label'=>"Middle East & North Africa", 'id'=>"10148",'data'=>"MiddleEastNorthAfrica",'parentid'=>"10147"),
    array('label'=>"Midlands", 'id'=>"10152",'data'=>"Midlands",'parentid'=>"10150"),
    array('label'=>"Napier", 'id'=>"10087",'data'=>"Napier",'parentid'=>"10085"),
    array('label'=>"Nelson", 'id'=>"10132",'data'=>"Nelson",'parentid'=>"10131"),
    array('label'=>"New Plymouth", 'id'=>"10083",'data'=>"NewPlymouth",'parentid'=>"10082"),
    array('label'=>"North Canterbury", 'id'=>"10115",'data'=>"NorthCanterbury",'parentid'=>"10113"),
    array('label'=>"North Shore & Northern Beaches", 'id'=>"10028",'data'=>"NorthShoreNorthernBeaches",'parentid'=>"1000"),
    array('label'=>"North West & Hills District", 'id'=>"10029",'data'=>"NorthWestHillsDistrict",'parentid'=>"1000"),
    array('label'=>"North West England", 'id'=>"10155",'data'=>"NorthWestEngland",'parentid'=>"10150"),
    array('label'=>"Northern England", 'id'=>"10154",'data'=>"NorthernEngland",'parentid'=>"10150"),
    array('label'=>"Northern Ireland", 'id'=>"10153",'data'=>"NorthernIreland",'parentid'=>"10150"),
    array('label'=>"Northern Suburbs", 'id'=>"10012",'data'=>"BrisbaneNorthernSuburbs",'parentid'=>"1004"),
    array('label'=>"Northern Suburbs", 'id'=>"10072",'data'=>"MelbourneNorthernSuburbs",'parentid'=>"1002"),
    array('label'=>"Northern Suburbs & Joondalup", 'id'=>"10051",'data'=>"NorthernSuburbsJoondalup",'parentid'=>"1009"),
    array('label'=>"Palmerston North", 'id'=>"10098",'data'=>"PalmerstonNorth",'parentid'=>"10097"),
    array('label'=>"Papakura & Franklin", 'id'=>"10120",'data'=>"PapakuraFranklin",'parentid'=>"1018"),
    array('label'=>"Parramatta & Western Suburbs", 'id'=>"10030",'data'=>"ParramattaWesternSuburbs",'parentid'=>"1000"),
    array('label'=>"PNG & Pacific Islands", 'id'=>"10145",'data'=>"PNGPacificIslands",'parentid'=>"10140"),
    array('label'=>"Porirua & Kapiti Coast", 'id'=>"10108",'data'=>"PoriruaKapitiCoast",'parentid'=>"1019"),
    array('label'=>"Queenstown & Wanaka", 'id'=>"10095",'data'=>"QueenstownWanaka",'parentid'=>"10093"),
    array('label'=>"Rest of Bay of Plenty", 'id'=>"10092",'data'=>"RestofBayofPlenty",'parentid'=>"10089"),
    array('label'=>"Rest of Canterbury", 'id'=>"10117",'data'=>"RestofCanterbury",'parentid'=>"10113"),
    array('label'=>"Rest of Gisborne", 'id'=>"10106",'data'=>"RestofGisborne",'parentid'=>"10104"),
    array('label'=>"Rest of Hawkes Bay", 'id'=>"10088",'data'=>"RestofHawkesBay",'parentid'=>"10085"),
    array('label'=>"Rest of Manawatu", 'id'=>"10100",'data'=>"RestofManawatu",'parentid'=>"10097"),
    array('label'=>"Rest of Marlborough", 'id'=>"10081",'data'=>"RestofMarlborough",'parentid'=>"10079"),
    array('label'=>"Rest of Northland", 'id'=>"10103",'data'=>"RestofNorthland",'parentid'=>"10101"),
    array('label'=>"Rest of Otago", 'id'=>"10096",'data'=>"RestofOtago",'parentid'=>"10093"),
    array('label'=>"Rest of Southland", 'id'=>"10112",'data'=>"RestofSouthland",'parentid'=>"10110"),
    array('label'=>"Rest of Taranaki", 'id'=>"10084",'data'=>"RestofTaranaki",'parentid'=>"10082"),
    array('label'=>"Rest of Tasman", 'id'=>"10133",'data'=>"RestofTasman",'parentid'=>"10131"),
    array('label'=>"Rest of Waikato", 'id'=>"10130",'data'=>"RestofWaikato",'parentid'=>"10126"),
    array('label'=>"Rest of Wellington Region", 'id'=>"10109",'data'=>"RestofWellingtonRegion",'parentid'=>"1019"),
    array('label'=>"Rest of West Coast", 'id'=>"10125",'data'=>"RestofWestCoast",'parentid'=>"10123"),
    array('label'=>"Rockingham & Kwinana", 'id'=>"10052",'data'=>"RockinghamKwinana",'parentid'=>"1009"),
    array('label'=>"Rodney & North Shore", 'id'=>"10121",'data'=>"RodneyNorthShore",'parentid'=>"1018"),
    array('label'=>"Rotorua", 'id'=>"10090",'data'=>"Rotorua",'parentid'=>"10089"),
    array('label'=>"Russia & Eastern Europe", 'id'=>"10135",'data'=>"RussiaEasternEurope",'parentid'=>"10134"),
    array('label'=>"Ryde & Macquarie Park", 'id'=>"10031",'data'=>"RydeMacquariePark",'parentid'=>"1000"),
    array('label'=>"Scotland", 'id'=>"10156",'data'=>"Scotland",'parentid'=>"10150"),
    array('label'=>"South East & Home Counties", 'id'=>"10157",'data'=>"SouthEastHomeCounties",'parentid'=>"10150"),
    array('label'=>"South West & M5 Corridor", 'id'=>"10033",'data'=>"SouthWestM5Corridor",'parentid'=>"1000"),
    array('label'=>"South West England", 'id'=>"10158",'data'=>"SouthWestEngland",'parentid'=>"10150"),
    array('label'=>"South-East Asia", 'id'=>"10146",'data'=>"SouthEastAsia",'parentid'=>"10140"),
    array('label'=>"Southern Suburbs & Logan", 'id'=>"10013",'data'=>"SouthernSuburbsLogan",'parentid'=>"1004"),
    array('label'=>"Southern Suburbs & Sutherland Shire", 'id'=>"10032",'data'=>"SouthernSuburbsSutherlandShire",'parentid'=>"1000"),
    array('label'=>"Sub-Saharan Africa", 'id'=>"10149",'data'=>"SubSaharanAfrica",'parentid'=>"10147"),
    array('label'=>"Taupo", 'id'=>"10128",'data'=>"Taupo",'parentid'=>"10126"),
    array('label'=>"Tauranga", 'id'=>"10091",'data'=>"Tauranga",'parentid'=>"10089"),
    array('label'=>"Thames & Coromandel", 'id'=>"10129",'data'=>"ThamesCoromandel",'parentid'=>"10126"),
    array('label'=>"Thames Valley & Oxford", 'id'=>"10159",'data'=>"ThamesValleyOxford",'parentid'=>"10150"),
    array('label'=>"Timaru & South Canterbury", 'id'=>"10116",'data'=>"TimaruSouthCanterbury",'parentid'=>"10113"),
    array('label'=>"USA & Canada", 'id'=>"10139",'data'=>"USACanada",'parentid'=>"10137"),
    array('label'=>"Waitakere & West Auckland", 'id'=>"10122",'data'=>"WaitakereWestAuckland",'parentid'=>"1018"),
    array('label'=>"Wales", 'id'=>"10160",'data'=>"Wales",'parentid'=>"10150"),
    array('label'=>"Wanganui", 'id'=>"10099",'data'=>"Wanganui",'parentid'=>"10097"),
    array('label'=>"Wellington Central", 'id'=>"2831",'data'=>"WellingtonCentral",'parentid'=>"1019"),
    array('label'=>"Western Europe", 'id'=>"10136",'data'=>"WesternEurope",'parentid'=>"10134"),
    array('label'=>"Western Suburbs", 'id'=>"10073",'data'=>"WesternSuburbs",'parentid'=>"1002"),
    array('label'=>"Western Suburbs & Ipswich", 'id'=>"10014",'data'=>"WesternSuburbsIpswich",'parentid'=>"1004"),
    array('label'=>"Whangarei", 'id'=>"10102",'data'=>"Whangarei",'parentid'=>"10101"),
    array('label'=>"All Sydney", 'id'=>"1000000",'data'=>"",'parentid'=>"1000"),
    array('label'=>"All Melbourne", 'id'=>"1002000",'data'=>"",'parentid'=>"1002"),
    array('label'=>"All Brisbane", 'id'=>"1004000",'data'=>"",'parentid'=>"1004"),
    array('label'=>"All Perth", 'id'=>"1009000",'data'=>"",'parentid'=>"1009"),
    array('label'=>"All Adelaide", 'id'=>"1007000",'data'=>"",'parentid'=>"1007"),
    array('label'=>"All Hobart", 'id'=>"1011000",'data'=>"",'parentid'=>"1011"),
    array('label'=>"All Darwin", 'id'=>"1013000",'data'=>"",'parentid'=>"1013"),
    array('label'=>"All Canberra", 'id'=>"3100000",'data'=>"",'parentid'=>"3100"),
    array('label'=>"All Gold Coast", 'id'=>"1005000",'data'=>"",'parentid'=>"1005")
    );


echo "Dit me thang Đạt";